version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  rest_api_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    depends_on:
      - postgres_db
volumes:
  postgres_db:
    driver: local